import { Post, User } from "./Interfaces";

export let users: User[] = [
  {
    id: 1,
    name: "Flávio",
    email: "flavio@flavio.com",
    senha: "flavio",
    idade: 100,
    role: "admin",
  },
  {
    id: 2,
    name: "Ana Silva",
    email: "ana.silva@email.com",
    senha: "anasenha",
    idade: 28,
    role: "user",
  },
  {
    id: 3,
    name: "Carlos Mendes",
    email: "carlos.mendes@email.com",
    senha: "carlos123",
    idade: 35,
    role: "user",
  },
  {
    id: 4,
    name: "Beatriz Costa",
    email: "beatriz.costa@email.com",
    senha: "bia456",
    idade: 22,
    role: "user",
  },
  {
    id: 5,
    name: "Rafael Souza",
    email: "rafael.souza@email.com",
    senha: "rafa789",
    idade: 40,
    role: "moderator",
  },
  {
    id: 6,
    name: "Juliana Almeida",
    email: "juliana.almeida@email.com",
    senha: "juju2024",
    idade: 31,
    role: "user",
  },
  {
    id: 7,
    name: "Lucas Fernandes",
    email: "lucas.fernandes@email.com",
    senha: "lucasf",
    idade: 27,
    role: "user",
  },
  {
    id: 8,
    name: "Mariana Rocha",
    email: "mariana.rocha@email.com",
    senha: "marirocha",
    idade: 29,
    role: "user",
  },
  {
    id: 9,
    name: "Pedro Henrique",
    email: "pedro.henrique@email.com",
    senha: "pedrinho",
    idade: 33,
    role: "moderator",
  },
  {
    id: 10,
    name: "Camila Dias",
    email: "camila.dias@email.com",
    senha: "camidias",
    idade: 26,
    role: "user",
  },
  {
    id: 11,
    name: "Thiago Lima",
    email: "thiago.lima@email.com",
    senha: "thiagol",
    idade: 38,
    role: "user",
  },
  {
    id: 12,
    name: "Fernanda Oliveira",
    email: "fernanda.oliveira@email.com",
    senha: "feroliveira",
    idade: 30,
    role: "user",
  },
  {
    id: 13,
    name: "Gustavo Pereira",
    email: "gustavo.pereira@email.com",
    senha: "gustavop",
    idade: 36,
    role: "user",
  },
  {
    id: 14,
    name: "Larissa Martins",
    email: "larissa.martins@email.com",
    senha: "larimartins",
    idade: 24,
    role: "user",
  },
  {
    id: 15,
    name: "Daniel Castro",
    email: "daniel.castro@email.com",
    senha: "danicastro",
    idade: 42,
    role: "admin",
  },
  {
    id: 16,
    name: "Aline Santos",
    email: "aline.santos@email.com",
    senha: "alinesantos",
    idade: 29,
    role: "user",
  },
  {
    id: 17,
    name: "Roberto Nascimento",
    email: "roberto.nascimento@email.com",
    senha: "robertonasc",
    idade: 45,
    role: "moderator",
  },
  {
    id: 18,
    name: "Patrícia Vieira",
    email: "patricia.vieira@email.com",
    senha: "pativieira",
    idade: 32,
    role: "user",
  },
  {
    id: 19,
    name: "Eduardo Ramos",
    email: "eduardo.ramos@email.com",
    senha: "eduramos",
    idade: 37,
    role: "user",
  },
  {
    id: 20,
    name: "Isabela Gomes",
    email: "isabela.gomes@email.com",
    senha: "isagomes",
    idade: 25,
    role: "user",
  },
];

export let posts: Post[] = [];
